package consts

const (
	BTCEUR_ID = 168
	ETHEUR_ID = 167
	LTCEUR_ID = 169
	XRPEUR_ID = 170
	XTHXXRP   = 173

	SIM_BTCEUR_ID_ORIGINAL = 3
	SIM_ETHEUR_ID_ORIGINAL = 1
	SIM_LTCEUR_ID_ORIGINAL = 2
	SIM_XRPEUR_ID_ORIGINAL = 4
	SIM_XTHXXRP_ID_ORIGINAL = 31

)